### ISSUE TITLE
Extract-text-webpack-plugin broken

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/blitz-js-view#6]
No idea when this happened. The `extractCSS: true` option in vue-loader at /webpack/base.config.js causes `extract-text-webpack-plugin` to throw this error: 
```
 ModuleBuildError: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-p
lugin for the usage example
      at Object.module.exports.pitch (D:\dev\nexus-stats\nexus-stats\node_modules\extract-text-webpack-plugin\loader.js:25:9)
      at runLoaders (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\NormalModule.js:194:19)
      at D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:364:11
      at D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:179:20
      at runSyncOrAsync (D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
      at D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:175:3
      at loadLoader (D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\loadLoader.js:36:3)
      at iteratePitchingLoaders (D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
      at runLoaders (D:\dev\blitz\blitz-js-view\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
      at NormalModule.doBuild (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\NormalModule.js:181:3)
      at NormalModule.build (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\NormalModule.js:274:15)
      at Compilation.buildModule (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:149:10)
      at factoryCallback (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:337:12)
      at NormalModuleFactory.create (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
      at _this.semaphore.acquire (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:237:13)
      at Semaphore.acquire (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\util\Semaphore.js:16:4)
      at iteratorFactory (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:235:20)
      at D:\dev\blitz\blitz-js-view\node_modules\async\dist\async.js:3083:16
      at eachOfArrayLike (D:\dev\blitz\blitz-js-view\node_modules\async\dist\async.js:1003:9)
      at eachOf (D:\dev\blitz\blitz-js-view\node_modules\async\dist\async.js:1051:5)
      at Object.eachLimit (D:\dev\blitz\blitz-js-view\node_modules\async\dist\async.js:3145:5)
      at Compilation.addModuleDependencies (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:217:12)
      at Compilation.processModuleDependencies (D:\dev\blitz\blitz-js-view\node_modules\webpack\lib\Compilation.js:202:8),
```
The vue-loader options accept additional keys which modify how loaders are used. Might be a starting point for fixes.

**Comment by Kaptard** [comment]
seems to be fixed with this
```
{
                test: /\.vue$/,
                loader: "vue-loader",
                options: {
                    extractCSS: true,
                    loaders: {
                        scss: extractSass.extract({
                            use: "!css-loader!sass-loader?"
                        })
                    }
                }
            }
```
Honestly don't know why though. Using `vue-style-loader!css-loader!sass-loader` and variants would throw other errors before.
